# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Ryuhaerang Choi
title: Human Computer Interaction Researcher
email: fkdfkd98@kaist.ac.kr
# email_title: Email (Email title override)
# phone: Your phone number (optional)
# phone_title: Phone (Phone title override)
website: https://withsun.github.io
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username:
github_username:  withSun
#stackoverflow_username: ""
#dribbble_username:
facebook_username: Ryuhaerang Choi
#flickr_username:
#instagram_username:
#linkedin_username:
#xing_username:
#pinterest_username:
youtube_username: Ryuhaerang Choi
#googleplus_username:
#orcid_username:

# Additional icon links
additional_links:
- title: Networking and Mobile Sysmtems Lab (NMSL)
  icon: 
  url: https://nmsl.kaist.ac.kr
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I am Ryuhaerang Choi, a master student who aims for a system that can permeate people's daily lives and make life more prosperous. I am studying at the <a href="https://nmsl.kaist.ac.kr">Networking & Mobile Systems Lab</a> at KAIST.
  People today have mobile devices all the time, so these devices are the right platforms to create the system I want to build. So, I am interested in ubiquitous sensing with mobile devices and network-connected objects around us, mHealth which can be an accessible medical tool, and mHCI for valuable interaction between digital devices and people.

content:
  - title: Publications # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Adapting to Unknown Conditions in Learning-based Mobile Sensing
        link: https://taesikgong.com/paper/TMC21_MetaSense_preprint.pdf
        link_text: paper
        description: | # this will include new lines to allow paragraphs
          Taesik Gong, Yeonsu Kim, **Ryuhaerang Choi**, Jinwoo Shin, and Sung-Ju Lee
          IEEE Transactions on Mobile Computing (IEEE TMC) (Accepted).
        additional_links:
          - title:  Website
            icon: fab fa-github
            url: https://nmsl.kaist.ac.kr/projects/metasense/


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
