# Site
repository: ryuhaerang.github.io/ryuhaerangchoi/
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Ryuhaerang Choi
title: Digital Healthcare Researcher
email: ryuhaerang.choi@kaist.ac.kr
# email_title: Email (Email title override)
# phone: Your phone number (optional)
# phone_title: Phone (Phone title override)
website: ryuhaerangchoi.com
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: haerang_hci
github_username:  Ryuhaerang
#stackoverflow_username: ""
#dribbble_username:
facebook_username: RyuhaerangChoi
#flickr_username:
#instagram_username:
linkedin_username: ryuhaerang-choi-75ba76233
#xing_username:
#pinterest_username:
#youtube_username: withSun
#googleplus_username:
#orcid_username:

# Additional icon links
#additional_links:
#- title: Networking and Mobile Systems Lab (NMSL)
#  icon: 
#  url: https://nmsl.kaist.ac.kr
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I am Ryuhaerang Choi, a Ph.D. student in <a href="https://nmsl.kaist.ac.kr">Networking & Mobile Systems Lab</a> at <a href="https://www.kaist.ac.kr/en/">KAIST</a>, advised by Prof. <a href="https://sites.google.com/site/wewantsj/">Sung-Ju Lee</a>. 
  My research centers around understanding individuals' behaviors reflecting cognitive processes and mental health. 
  I develop intervention systems to address mental health challenges based on this understanding.
  I aim to promote mental well-being and facilitate positive behavior changes through practical interventions, making a meaningful contribution towards building a healthier society.

  <br>I have been fortunate to work closely with Prof. <a href="https://faculty.cc.gatech.edu/~jkim693/">Jennifer G. Kim</a> and Prof. <a href="https://orsonxu.com/?section=1">Xuhai "Orson" Xu</a>, with whom I am currently collaborating.
  I have also had the privilege of working with Prof. <a href="https://galaxytourist.notion.site/Hwajung-Hong-cc10b0291bbe4ca38dbf4882cd687423">Hwajung Hong</a> and Prof. <a href="https://ic.kaist.ac.kr/members">Uichin Lee</a> in earlier projects. 
  I was a research intern at <a href="https://www.bell-labs.com/#gref">Nokia Bell Labs</a>, mentored by Dr. <a href="https://sites.google.com/view/sjitiit/home">Soumyajit Chatterjee</a>, Dr. <a href="https://dispathis.com">Dimitris Spathis</a>, and Dr. <a href="https://mmalekzadeh.github.io">Mohammad Malekzadeh</a>.
  
  <br>Research Interests: Digital Healthcare, Human-Centered Computing for Health, Human-Centered AI, Interaction Design
  - <a href="https://drive.google.com/file/d/1ga-54KU_h7bz6NE16qCDWBFeNl870XZe/view?usp=sharing">**Curriculum Vitae**</a>


content:
  - title: Latest News
    layout: text
    content: | # this will include new lines to allow paragraphs
      <br>**May 2025** Paper Accepted at MobiSys Workshop'25
      <br>**Mar 2025** Paper (Private Yet Social) Won a Best Paper Honorable Mention at CHI'25
      <br>**Feb 2025** Invited Talk at the SIGCHI-Sponsored Top Conference Session at HCI Korea
      <br>**Jan 2025** Paper (Private Yet Social) Accepted at CHI'25
      <br>**Dec 2024** Paper (SoundCollage) Accepted at ICASSP'25
      <br>**Nov 2024** Invited Talk at Google ExploreCSR Journey of Research Workshop
      <br>**May 2024** FoodCensor Won a Best Paper Honorable Mention at CHI'24
      <br>**Mar 2024** Paper Accepted at ICML Workshop'24
      <br>**Jan 2024** Paper (FoodCensor) Accepted at CHI'24
      <br>**Jul 2023** Research internship at Nokia Bell Labs, Cambridge, UK (Jul-Sep)
      <br>**Feb 2023** Student Chair at Google ExploreCSR Rising Stars Workshop
#<br>**Nov 2022** Paper Presentation (#StressTrendmeter) at CSCW'22
#<br>**Oct 2022** Paper (MetaSense++) published at IEEE TMC'22
#<br>**Aug 2022** Student Steering Committee at 2022 Google ExploreCSR Women Tech Stars Workshop 
#<br> 2023 Google ExploreCSR Rising Stars Workshop on Feb 24
#<br> 2022 Google ExploreCSR Women Tech Stars Workshop on Aug 26
#<br>**June 2022** Demo (#StressTrendmeter) at MobiSys'22
#<br>**Feb 2022** Student Volunteer at TEI 2022
#<br>**Jan 2022** Student Chair at 2022 HCI@KAIST Winter Seminar on Jan 21
#<br>**Dec 2021** Student Chair at 2021 Fall in HCI@KAIST on Dec 3-7
#<br>**Aug 2021** Continue my research as a Ph.D student in NMSL at KAIST
#<br>**Jul 2021** Interactivity Chair at 2021 HCI@KAIST Summer Workshop on Jul 22
#<br>**Dec 2020** Presentation at CSCW Asia Winter School 2020 on Dec 18-19
#<br>**Aug 2020** Presentation at 2020 HCI@KAIST Summer Workshop
      
  - title: Education
    layout: list
    content:
      - layout: top
        title: <a href="https://www.kaist.ac.kr/en/">KAIST</a>, Republic of Korea
        sub_title: Ph.D. Candidate in Electrical Engineering, Advisor &#58; Prof. <a href="https://sites.google.com/site/wewantsj/"><b>Sung-Ju Lee</b></a>
        caption: 2021.08 - Present
    
      - layout: top
        title: <a href="https://www.kaist.ac.kr/en/">KAIST</a>, Republic of Korea
        sub_title: M.S. in Computer Science, Advisor &#58; Prof. <a href="https://sites.google.com/site/wewantsj/"><b>Sung-Ju Lee</b></a>
        caption: 2019.08 - 2021.08
          
      - layout: top
        title: <a href="https://eng.inha.ac.kr/eng/index.do">Inha University</a>, Republic of Korea
        sub_title: B.S. in Computer Science (Summa Cum Laude)
        caption: 2016.03 - 2019.08 (Early Graduation)  

  - title: Work Experience
    layout: list
    content:
      - layout: top
        title: Device Intelligence Team at <a href="https://www.bell-labs.com/#gref">Nokia Bell Labs</a>, Cambridge, UK
        sub_title: Research Intern
        caption: 2023.07 - 2023.09


  - title: Publications # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top
        title: Preprints
      - layout: top
        title: <a href="https://arxiv.org/abs/2509.15289">&#34;Collective Voice&#58; Recovered-Peer Support Mediated by An LLM-Based Chatbot for Eating Disorder Recovery&#34;</a>
        description: | 
          **Ryuhaerang Choi**, Taehan Kim\*, Subin Park\*, Seohyeon Yoo, Jennifer G. Kim, and Sung-Ju Lee
          <br>arXiv (Under review)

      - layout: top
        title: <a href="http://arxiv.org/abs/2311.05920">&#34;Impact Ambivalence&#58; How People with Eating Disorders Get Trapped in the Perpetual Cycle of Digital Food Content Engagement&#34;</a>
        description: | 
          **Ryuhaerang Choi**, Subin Park, Sujin Han, Jennifer G. Kim, and Sung-Ju Lee
          <br>arXiv (Under review)

      - layout: top
        title: Conferences and Journals

      - layout: top
        title: <a href="">&#34;Recovery Is Relational&#58; Everyday Support Needs in Eating Disorder Recovery with Patients <em>and</em> Their Supporters&#34;</a>
        description: | 
          **Ryuhaerang Choi**, Seohyeon Yoo, Xuhai "Orson" Xu, and Sung-Ju Lee
          <br>*ACM Conference on Human Factors in Computing Systems (**ACM CHI 2026**)* (Acceptance Rate: 25.3%)
        
      - layout: top
        title: <a href="https://dl.acm.org/doi/full/10.1145/3706598.3713485">&#34;Private Yet Social&#58; How LLM Chatbots Support and Challenge Eating Disorder Recovery&#34;</a>
        additional_links:
          - title: Presentation
            icon: fas fa-video
            url: https://youtu.be/eUKD5Sb6ytc?si=3XtbbSyLPenCM8mE
          - title: Website
            icon: fas fa-globe
            url: https://nmsl.kaist.ac.kr/projects/chatbot4ed/
        description: | 
          **Ryuhaerang Choi**, Taehan Kim, Subin Park, Jennifer G. Kim, and Sung-Ju Lee
          <br>*ACM Conference on Human Factors in Computing Systems (**ACM CHI 2025**)* (Acceptance Rate: 25.1%)
          <br>üèÖBest Paper Honorable Mention Award (Top 5%)
          
      - layout: top
        title: <a href="https://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=10890645">&#34;SoundCollage&#58; Automated Discovery of New Classes in Audio Datasets&#34;</a>
        additional_links:
          - title: Presentation
            icon: fas fa-video
            url: https://drive.google.com/file/d/1e5P373nTUTKnss4yQZeHSo7yhPVMFTqO/view?usp=share_link
          - title: Code
            icon: fas fa-code
            url: https://github.com/nokia-bell-labs/audio-class-discovery
        description: | 
          **Ryuhaerang Choi**, Soumyajit Chatterjee, Dimitris Spathis, Sung-Ju Lee, Fahim Kawsar, and Mohammad Malekzadeh
          <br>*IEEE International Conference on Acoustics, Speech, and Signal Processing (**IEEE ICASSP 2025**)*
          
      - layout: top
        title: <a href="https://dl.acm.org/doi/abs/10.1145/3613904.3641984">&#34;FoodCensor&#58; Promoting Mindful Digital Food Content Consumption for People with Eating Disorders&#34;</a>
        additional_links:
          - title: Presentation
            icon: fas fa-video
            url: https://youtu.be/2FYkHdRfV-0?si=-PsX2QC4ytjcrtI8
          - title: Website
            icon: fas fa-globe
            url: https://nmsl.kaist.ac.kr/projects/foodcensor/
          - title: Code
            icon: fas fa-code
            url: https://github.com/Ryuhaerang/FoodCensor
        description: | 
          **Ryuhaerang Choi**, Subin Park, Sujin Han, and Sung-Ju Lee
          <br>*ACM Conference on Human Factors in Computing Systems (**ACM CHI 2024**)* (Acceptance Rate: 26.3%)
          <br>üèÖBest Paper Honorable Mention Award (Top 5%)
        
      - layout: top
        title: <a href="https://dl.acm.org/doi/abs/10.1145/3555612">&#34;You Are Not Alone&#58; How Trending Stress Topics Brought &#35;Awareness and &#35;Resonance on Campus&#34;</a>
        additional_links:
          - title: Presentation
            icon: fas fa-video
            url: https://youtu.be/u_lSLpPVbFg?si=IiZNzxVLHMF3FpbR
          - title: Website
            icon: fas fa-globe
            url: https://nmsl.kaist.ac.kr/projects/stresstrendmeter/
        description: | # this will include new lines to allow paragraphs
          **Ryuhaerang Choi**, Chanwoo Yun, Hyunsung Cho, Hwajung Hong, Uichin Lee, and Sung-Ju Lee
          <br>*ACM Conference on Computer-Supported Cooperative Work and Social Computing (**ACM CSCW 2022**)*

      - layout: top
        title: <a href="https://ieeexplore.ieee.org/abstract/document/9361223">&#34;Adapting to Unknown Conditions in Learning-based Mobile Sensing&#34;<a>
        additional_links:
          - title: Website
            icon: fas fa-globe
            url: https://nmsl.kaist.ac.kr/projects/metasense/
          - title: Code
            icon: fas fa-code
            url: https://github.com/TaesikGong/MetaSense_public
        description: | # this will include new lines to allow paragraphs
          Taesik Gong, Yeonsu Kim, **Ryuhaerang Choi**, Jinwoo Shin, and Sung-Ju Lee
          <br>*IEEE Transactions on Mobile Computing (**IEEE TMC 2022**)*

      - layout: top
        title: Posters, Demos, and Workshop Papers

      - layout: top
        title: <a href="https://dl.acm.org/doi/10.1145/3742460.3742982">&#34;CrashSniffer&#58; UWB-Based Anchor-Free Pedestrian Collision Prediction for Personal Mobility Vehicles&#34;</a>
        description: | # this will include new lines to allow paragraphs
          Taeckyung Lee, Juseung Lee, **Ryuhaerang Choi**, Seungjoo Lee, Hyeongheon Cha, Hyungjun Yoon, Song Min Kim, Sangwook Bak, Sung-Ju Lee
          <br>**ACM MobiSys 2025** *Environmental Sensing Systems for Smart Cities (EnvSys) Workshop*

      - layout: top
        title: <a href="https://drive.google.com/file/d/17iq_qG2wQQ954OkJL3FFBXJ5gkXKp0rW/view?usp=sharing">&#34;Pushing the Decision Boundaries&#58; Discovering New Classes in Audio Data&#34;</a>
        description: | # this will include new lines to allow paragraphs
          **Ryuhaerang Choi**, Soumyajit Chatterjee, Dimitris Spathis, Fahim Kawsar, and Mohammad Malekzadeh
          <br>**ICML 2024** *Data-centric Machine Learning Research (DMLR) Workshop*
      
      - layout: top
        title: <a href="https://dl.acm.org/doi/abs/10.1145/3498361.3538672">&#34;Facilitating Instant Interactions for Stressful Experiences Sharing and Peer Support&#34;</a>
        description: | # this will include new lines to allow paragraphs
          **Ryuhaerang Choi**, Chanwoo Yun, Hyungsung Cho, Hwajung Hong, Uichin Lee, and Sung-Ju Lee
          <br>**ACM MobiSys 2022 Demos**

  - title: Academic Services
    layout: text
    content: | # this will include new lines to allow paragraphs
      **ACM CSCW Program Committee** 24
      <br>**ACM TEI Student Volunteer** 22
      <br>**Reviewer** 
      <br>&nbsp;&nbsp;**HCI**
      <br>&nbsp;&nbsp;&nbsp;&nbsp;ACM CHI 23-26
      <br>&nbsp;&nbsp;&nbsp;&nbsp;ACM CSCW 22-24
      <br>&nbsp;&nbsp;&nbsp;&nbsp;ACM IMWUT 25
      <br>&nbsp;&nbsp;&nbsp;&nbsp;ACM DIS 24-25
      <br>&nbsp;&nbsp;&nbsp;&nbsp;ACM MobileHCI 25
      <br>&nbsp;&nbsp;**Health**
      <br>&nbsp;&nbsp;&nbsp;&nbsp;JMIR 25
      <br>&nbsp;&nbsp;&nbsp;&nbsp;ACM HEALTH 25
      <br>&nbsp;**AI/ML**
      <br>&nbsp;&nbsp;&nbsp;&nbsp;DMLR@ICML 24
      
      <br>**Steering Committee Member**
      <br>&nbsp;<a href="https://kaist-explorecsr.github.io/index.html">KAIST ExploreCSR (sponsored by Google Research)</a> '22 '23
      <br>&nbsp;<a href="https://hci.kaist.ac.kr">HCI@KAIST</a> '21 '22

footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
