# Site
repository: withSun/withSun.github.io
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Ryuhaerang Choi
title: Human Computer Interaction Researcher
email: fkdfkd98@kaist.ac.kr
# email_title: Email (Email title override)
# phone: Your phone number (optional)
# phone_title: Phone (Phone title override)
website: https://withsun.github.io
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username:
github_username:  withSun
#stackoverflow_username: ""
#dribbble_username:
facebook_username: RyuhaerangChoi
#flickr_username:
#instagram_username:
#linkedin_username:
#xing_username:
#pinterest_username:
#youtube_username: withSun
#googleplus_username:
#orcid_username:

# Additional icon links
#additional_links:
#- title: Networking and Mobile Sysmtems Lab (NMSL)
#  icon: 
#  url: https://nmsl.kaist.ac.kr
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I am Ryuhaerang Choi, a master student who aims for a system that can permeate people's daily lives and make life more prosperous. I am studying at the <a href="https://nmsl.kaist.ac.kr">Networking & Mobile Systems Lab</a> at KAIST.
  People today have mobile devices all the time, so these devices are the right platforms to create the system I want to build. So, I am interested in mHCI for valuable interaction between digital devices and people, mHealth which can be an accessible medical tool, and ubiquitous sensing with mobile devices and network-connected objects around us.
  - <a href="https://drive.google.com/file/d/1ga-54KU_h7bz6NE16qCDWBFeNl870XZe/view?usp=sharing">**Curriculum Vitae**</a>


content:
  - title: Education
    layout: list
    content:
      - layout: top
        title: <a href="https://www.kaist.ac.kr/en/">KAIST</a>, Republic of Korea
        sub_title: M.S. Candidate in Computer Science, Advisor &#58; Prof. <a href="https://sites.google.com/site/wewantsj/"><b>Sung-Ju Lee</b></a>
        caption: 2019.08 - Present
          
      - layout: top
        title: <a href="https://eng.inha.ac.kr/eng/index.do">Inha University</a>, Republic of Korea
        sub_title: B.S. in Computer Science (Summa Cum Laude)
        caption: 2016.03 - 2019.08 (Early Graduation)
  
  - title: Publications # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top
        title: <a href="https://taesikgong.com/paper/TMC21_MetaSense_preprint.pdf">&#34;Adapting to Unknown Conditions in Learning-based Mobile Sensing&#34;<a>
        link: https://nmsl.kaist.ac.kr/projects/metasense/
        link_text: üåêWebsite
        description: | # this will include new lines to allow paragraphs
          Taesik Gong, Yeonsu Kim, **Ryuhaerang Choi**, Jinwoo Shin, and Sung-Ju Lee
          <br>*IEEE Transactions on Mobile Computing (**IEEE TMC**) (Accepted).*
        additional_links:
          - title:  Website
            url: https://nmsl.kaist.ac.kr/projects/metasense/
  
  - title: Latest News
    layout: list
    content: | # this will include new lines to allow paragraphs
      **Dec 2020** SIGCHI CSCW Asia Winter School (AWS) 2020 on Dec 18-19.
      **Aug 2020** Presentation at 2020 HCI@KAIST Summer Workshop

  - title: Research Interests
    layout: list
    content:
      - layout: left
        title: Mobile HCI
        sub_title: mHCI
        description: | # this will include new lines to allow paragraphs
          Human-computer interection (HCI) studies the interaction between humans and computers including both HW and SW. One of the objectives of mHCI is to build a mobile system to improve the quality of human life.
      - layout: left
        title: Mobile Health
        sub_title: mHealth
        description: |
          Mobile healthcare industry has been in the limelight for years. mHealth is the term used for health-related service supported by mobile devices. The examples of mHealth applications are provision of medical information to patients, real-time monitoring of biometric signal, telemedicine, etc.
      - layout: left
        title: Ubiquotous Sensing
        description: | # this will include new lines to allow paragraphs
          Ubiquitous sensing means utilizing network-connected digital sensors in a given environment. We can detect amount of light, amplitude of sound, frequency of vibration, etc. The combination of ubiquitous sensing and ML can make objects around us intelligent.


#  - title: Research Projects
#    layout: list
#    content:
#      - layout: left
#        title: Project title
#        sub_title: sub title
#        caption: caption
#        link: link
#        quote: >
#          Short description of the company (optional)
#        description: | # this will include new lines to allow paragraphs
#          Description

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
